### ISSUE TITLE
请问文章中的分割图片是怎么生成的呀

### ISSUE THREAD

**Issue by AAAdecade** [gyyang23/RDRNet#6]
您好！非常感谢您的杰出工作，在复现该项目时，我也想输出您文中的类似图片，请问应该怎么输出，需要运行什么代码指令？
期待您的回复，祝您科研顺利，天天开心！感谢！

![image](https://github.com/user-attachments/assets/602da902-d2f0-40ca-9956-1492b075d364)

**Comment by zhoukaiyu123** [comment]
请问您复现了comvid数据集吗精度有达到论文中的精度吗

**Comment by gyyang23** [comment]
> 请问能帮助我一下吗

<img width="484" alt="19931e55844348ddf9876930dd0cf26" src="https://github.com/user-attachments/assets/42856feb-50eb-4bcb-a6b5-9c6ee72f662e">
1.首先在配置文件里将test_evaluator进行更改
2.运行CUDA_VISIBLE_DEVICES=0 python mmsegmentation/tools/test.py rdrnet-s-simple_2xb6-120k_cityscapes-1024x1024.py ./weight/seg/checkpoint，运行结束以后二值图片生成到./results/seg/文件夹里
3.二值文件上色，可参照（https://blog.csdn.net/weixin_43889476/article/details/124135249）

**Comment by gyyang23** [comment]
上述说的比较麻烦，./mmsegmentation/tools/test.py中可能存在更快捷的方式。

**Comment by AAAdecade** [comment]
> 上述说的比较麻烦，./mmsegmentation/tools/test.py中可能存在更快捷的方式。

非常感谢您的杰出工作和指导，请问如何测量推理速度？我使用了mmsegmentation的tools/analysis_tools/benchmark.py  进行FPS测试，其结果下降比较严重，只有90多的fps，请问有速度测量的代码吗？谢谢您，祝您学习生活都一切顺利

**Comment by gyyang23** [comment]
backbone=dict(
        type='RDRNet',
        in_channels=3,
        channels=32,
        ppm_channels=128,
        num_blocks_per_stage=[4, 3, [5, 4], [5, 4], [1, 1]],
        norm_cfg=dict(type='BN', requires_grad=True, momentum=0.03, eps=0.001),
        align_corners=False,
        deploy=True,  **#False->True**
),

then tools/analysis_tools/benchmark.py

**Comment by AAAdecade** [comment]
> backbone=dict( type='RDRNet', in_channels=3, channels=32, ppm_channels=128, num_blocks_per_stage=[4, 3, [5, 4], [5, 4], [1, 1]], norm_cfg=dict(type='BN', requires_grad=True, momentum=0.03, eps=0.001), align_corners=False, deploy=True, **#False->True** ),
> 
> then tools/analysis_tools/benchmark.py
非常感谢您的回复，我听取了您的建议，在单个3090gpu重新运行了tools/analysis_tools/benchmark.py文件，达到了124fps，与文中仍有一点差距，但其实目前的推理速度fps已经很让我惊讶了。另外，我使用mmsegmentation包中复现的ddrnet只有95fps、pidnet只有70左右的fps，与原文差异巨大！我不清纯是什么原因导致的，请问您遇到过这样的问题吗( tools/analysis_tools/benchmark.py是因为使用该文件并且重构代码框架导致的嘛)，最后我想问怎么才能跑出rdrnet_slim 134.6的FPS? 希望能得到您的指点。非常感谢！祝您学习工作一切顺利！
![image](https://github.com/user-attachments/assets/ce43110b-e829-4173-b3e6-306f06732c8e)

**Comment by gyyang23** [comment]
1.我们通过大量的实验发现，在相同的GPU（例如3090）但是不相同的平台（CPU可能不同等等）上进行FPS测试时，结果是不一致的。
2.我们在FPS测试时是将CONV与BN进行了融合。为了公平比较，表2标”*“、表3和表4中的模型都是将CONV与BN进行了融合。我们的代码tools/analysis_tools/benchmark.py中已经实现将CONV与BN进行了融合。所以你可以使用我们的代码测试DDRNet。

**Comment by AAAdecade** [comment]
> 1.我们通过大量的实验发现，在相同的GPU（例如3090）但是不相同的平台（CPU可能不同等等）上进行FPS测试时，结果是不一致的。 2.我们在FPS测试时是将CONV与BN进行了融合。为了公平比较，表2标”*“、表3和表4中的模型都是将CONV与BN进行了融合。我们的代码tools/analysis_tools/benchmark.py中已经实现将CONV与BN进行了融合。所以你可以使用我们的代码测试DDRNet。

明白了，感谢指导。谢谢您帮助小白的我，祝您科研顺利，paper多多！

**Comment by AAAdecade** [comment]
> > 请问能帮助我一下吗
> 
> <img alt="19931e55844348ddf9876930dd0cf26" width="484" src="https://private-user-images.githubusercontent.com/49688633/384694877-42856feb-50eb-4bcb-a6b5-9c6ee72f662e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDc4MDUsIm5iZiI6MTczMTUwNzUwNSwicGF0aCI6Ii80OTY4ODYzMy8zODQ2OTQ4NzctNDI4NTZmZWItNTBlYi00YmNiLWE2YjUtOWM2ZWU3MmY2NjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE0MTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDNiMjg2ZGI1NDUwMjZiYmViOWUwNThhZWIxYTEzMzM5ODg3NjY5MGFkYTRmZWQ2YzJjMWViMzBiOTQzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4wPSeWstW2_T6EMGF1pcs7Lq5uF76-lz58_IP9YgHrA">
> 1.首先在配置文件里将test_evaluator进行更改 2.运行CUDA_VISIBLE_DEVICES=0 python mmsegmentation/tools/test.py rdrnet-s-simple_2xb6-120k_cityscapes-1024x1024.py ./weight/seg/checkpoint，运行结束以后二值图片生成到./results/seg/文件夹里 3.二值文件上色，可参照（[https://blog.csdn.net/weixin_43889476/article/details/124135249）](https://blog.csdn.net/weixin_43889476/article/details/124135249%EF%BC%89)

您好！我修改了test_evaluator的配置，成功保存了500个灰色的图片文件，然而我在根据您提供的csdn博客进行图片上色时遇到了困难，我将该博客的代码复制运行，处理后的500个val图片文件变得很不雅观，非常错乱（如下图）。请问您能发给我一份可以正常运行的，将灰色图像变为彩色图像的py文件吗？这是我的邮箱 tcwang26@163.com    恳求您能帮我一下，也请原谅我的冒昧请求！谢谢您。
![frankfurt_000001_003056_leftImg8bit](https://github.com/user-attachments/assets/a6af7cea-4878-47d3-8084-fce9d7fb765e)

**Comment by AAAdecade** [comment]
非常感谢，目前我已经解决了该问题。

**Comment by zhoukaiyu-zky** [comment]
请问您在测试时出现了黑色部分分割不出来的情况吗
![Uploading frankfurt_000000_000294_leftImg8bit.png…]()
![Uploading frankfurt_000000_000294_leftImg8bit.png…]()
